### ISSUE TITLE
Question: Using CLion, Compiling to Native

### ISSUE THREAD

**Issue by webern** [mbasso/asm-dom#20]
Thank you for your work.

I have a question. In order to get the benefit of C++ IDE's like CLion, we would need to be able to compile the bulk of our code to native, otherwise Clang/GCC, and thus the IDE would throw up its hands.

Is it possible to compile some or all of a project to native for the purpose of IDE tooling a C++ unit tests?

Let's assume for a moment that we would be fine forgoing CSX for this purpose.

**Comment by webern** [comment]
I'm finding some things related to using CLion and Cmake

**Comment by mbasso** [comment]
Hi @webern,
Have you solved your issue?

**Comment by webern** [comment]
No I haven't, but I better understand what is involved. Basically I need to figure out how to make a Cmake file for an emscripted project. If I can do that, then I believe CLion will work as it would with a normal C++ project.

I'm about the existence of emmake emcc and emcmake. I'm pretty sure I need to make a Cmakelists.txt file that does the right thing when it is called from the real cmake executable (not, for example emcmake).

It's non-trivial, but I at least know what I'm trying to do now.
