### ISSUE TITLE
language clarity

### ISSUE THREAD

**Issue by paul-hammant** [mbasso/asm-dom#3]
I think you should:

    `s/Web App/browser app/g`

Because web-apps in C++ were regular in the 90's via CGI-BIN and Apache. Doesn't need to be capitalized, either.

**Comment by mbasso** [comment]
I haven't thought about it!
What about `A minimal WebAssembly virtual DOM to build C++ SPA (Single page applications)`?

**Comment by paul-hammant** [comment]
Sure, anything except "Web App" as that's inextricably linked with server side.

**Comment by mbasso** [comment]
awesome, thank you!
