### ISSUE TITLE
SVG Support is broken

### ISSUE THREAD

**Issue by HappyCerberus** [mbasso/asm-dom#33]
**General Information**

- [ x ] Bug

**Description**

SVG elements are generated in uppercase which seems to break both Firefox & Chrome.
Here is a demo:
https://github.com/HappyCerberus/asm-dom-boilerplate/tree/demo

**Comment by mbasso** [comment]
Hi @HappyCerberus,
I have just published a fix with asm-dom@0.6.4 🎉.
Thank you for reporting this bug and feel free to re-open the issue if needed.
