### ISSUE TITLE
Inline Example in README.md is missing a closing parenthesis.

### ISSUE THREAD

**Issue by ColeDeanShepherd** [mbasso/asm-dom#7]
Inline Example in README.md is missing a closing parenthesis on line 78, after `std::string("root"),`.

```
  // Patch into empty DOM element â€“ this modifies the DOM as a side effect
  patch(
    emscripten::val::global("document").call<emscripten::val>(
    "getElementById",
    std::string("root"),
    vnode
  );
```

**Comment by mbasso** [comment]
Hi @ColeDeanShepherd,
thank you a lot for opening this issue and for following through with a PR 😄

**Comment by ColeDeanShepherd** [comment]
Glad I could help @mbasso, love your project!
