### ISSUE TITLE
Support SSR(Server Side Rendering)?

### ISSUE THREAD

**Issue by vbalien** [mbasso/asm-dom#9]
Do you plan to support SSR?
I need Pre-Render function on the server.

**Comment by mbasso** [comment]
Hi @vbalien,
sure! At the moment I'm working on [gccx](https://github.com/mbasso/gccx), a JSX parser for asm-dom, after that I'll develop this feature. I think that it will be a strong improvement for the project 😄

**Comment by mbasso** [comment]
Just published asm-dom@0.4.0 with 2 new functions to implement SSR 🎉
Please let me know if you have some questions, ideas and so on 😄
